### ISSUE TITLE
[Storybook] The web component is not loaded

### ISSUE THREAD

**Issue by osamamaruf** [hontas/svelte-web-component#2]
In the storybook demo the web component has not actually loaded.
**Expected Behavior**
Shadow DOM should be observed
![image](https://user-images.githubusercontent.com/34508971/87002834-e572fd00-c1d3-11ea-918f-f76597fb262a.png)

**Current Behavior**
No shadow dom is observed.

Let me know what you think about this. Also happy to contribute to the repo.

**Comment by hontas** [comment]
Oh I had forgotten I created this 😅 thanks 4 the feedback. Gonna update this to what I've learned over the past 7 months. 
- What would you like to contribute with?
- Where do you see this going?
Thanks again.

**Comment by hontas** [comment]
@osamamaruf now I get what you mean 🤦 My setup was that you had to run `npm run dev` before `npm run storybook` but I have changed that now so that storybook can build the svelte-files.
